### PR TITLE
Refactoring and quality of life improvements

### PR DESCRIPTION
**Pull request by kihayu**
I hope you are doing well. I recently found your project, and think it has a lot of potential.

I made some refactoring and quality-of-life changes that I hope will make the code more maintainable and easier to work with. If you have any concerns about these changes or if any issues need to be addressed, please don't hesitate to let me know. I want to ensure that the project is as practical and functional as possible, and I'm happy to revert any changes that aren't meeting that goal or if you think that these changes wouldn't be as useful.

In the future, I would like to improve the stability of the extension. However, this will take more time and probably needs some more refactoring.

(85% of this text was generated by ChatGPT)

### CODE REVIEW

**Review by acheong08 — APPROVED** [review]
Thanks. This is a lot better. (It was my first time writing proper JavaScript so it is a mess)

**Comment by acheong08** [comment]
> (85% of this text was generated by ChatGPT)

I should really start using ChatGPT to code. I'm still old school despite working with ChatGPT so much

**Comment by acheong08** [comment]
Tested. It works well.

**Comment by irgolic** [comment]
Thanks @acheong08 for this wonderful solution, and @kihayu for contributing.

@kihayu, if you don't mind me asking – what exactly did your workflow in creating this pull request look like? Do you have any tricks to share?

**Comment by kihayu** [comment]
> > (85% of this text was generated by ChatGPT)
> 
> I should really start using ChatGPT to code. I'm still old school despite working with ChatGPT so much

I'm also new to using ChatGPT for coding. I think there was a misunderstanding. With the generated text I mean the description of the pr. The code was written by me.

**Comment by acheong08** [comment]
Ah. That makes a lot more sense. The code is way too high quality to be by ChatGPT. Thank you so much for your contribution

**Comment by kihayu** [comment]
> Thanks @acheong08 for this wonderful solution, and @kihayu for contributing.
> 
> @kihayu, if you don't mind me asking – what exactly did your workflow in creating this pull request look like? Do you have any tricks to share?

No problem. I can share how I developed these features. This is quite similar to how I do it at work.

* I created a branch and named it so, that the naming represents the main changes in what I did. Regarding the "feature/" prefix, search for "git branch naming conventions" and read about it. It will help to keep things a bit more organized.
* After that I coded one feature at a time and tried to commit similar changes at once.
* Then I tested everything, fixed bugs, and committed the changes. This step repeats as long as necessary.
* At the end I created the PR and wrote a description. In the future, I will write down what changes happened in the code. This time it wouldn't make that much sense because the changes were only some refactoring and structure changes

**Comment by acheong08** [comment]
> I created a branch and named it so, that the naming represents the main changes in what I did. Regarding the "feature/" prefix, search for "git branch naming conventions" and read about it. It will help to keep things a bit more organized.

I will start doing that from now on. I have seen this style used in most large repos but never implemented it myself due to laziness.

**Pull request merged**
